# Generated by Django 4.0.4 on 2022-06-01 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_customercomplaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customercomplaint',
        ),
    ]
