# Generated by Django 4.0.4 on 2022-06-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_customercomplaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercomplaint',
            old_name='Description',
            new_name='description',
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customercomplaint',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
