# Generated by Django 4.0.4 on 2022-06-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_description_customercomplaint_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint_against_supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, max_length=10, null=True)),
                ('inspected_qty', models.CharField(blank=True, max_length=255, null=True)),
                ('complaint_qty', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customercomplaint',
            name='date',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
