# Generated by Django 4.0.4 on 2022-06-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_complaint_against_supplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='material_error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('inspected_qty', models.CharField(blank=True, max_length=255, null=True)),
                ('complaint_qty', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('skunumber', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
