# Generated by Django 4.0.4 on 2022-06-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_material_error'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='material_error',
            new_name='material_error_model',
        ),
    ]
