# Generated by Django 4.0.4 on 2022-06-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_material_error_material_error_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='material_error_model',
            name='date',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
