# Generated by Django 4.0.4 on 2022-06-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_material_error_model_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_against_supplier',
            name='sku_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
